### ISSUE TITLE
Vertical dmenu

### ISSUE THREAD

**Issue by flohw** [klaasb/passdmenu#16]
Hello,

I recently moved from buttercup to pass as buttercup has some annoying bugs... I wanted to user passdemnu to ease password clipboard copy but I wanted to list passwords one per line instead of all on the same line like dmenu_run does.

I tried `passdmenu -D "/usr/local/bin/dmenu -l 3"` but I get the following error:
```text
Traceback (most recent call last):
  File "/usr/bin/passdmenu", line 327, in <module>
    main()
  File "/usr/bin/passdmenu", line 283, in main
    choice = dmenu(choices, dmenu_opts, args.dmenu_bin)
  File "/usr/bin/passdmenu", line 42, in dmenu
    dmenu = subprocess.Popen([path] + args,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/dmenu -l 3'
```

Is there a way to pass some paramters to dmenu command or it will require some development?

Thank you

**Comment by flohw** [comment]
Fixed by using passdmenu proposed on passwordstore page.
